packages:
  - 'web'

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - esbuild
  - protobufjs

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  esbuild: true
  protobufjs: true
  sharp: true
  vue-demi: true
  workerd: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.4'
  - '@tanstack/vue-query@5.101.4'
