packages:
  - 'web'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.4'
  - '@tanstack/vue-query@5.101.4'
