export const SHOP_ORDER_DETAIL_ROUTE = 'app-shop-order-detail-page';
export const DROPSHIP_ORDER_DETAIL_ROUTE = SHOP_ORDER_DETAIL_ROUTE;
export const DROPSHIP_ORDER_DETAIL_PROCESSING_ROUTE = SHOP_ORDER_DETAIL_ROUTE;
export const DROPSHIP_ORDER_DETAIL_READY_FOR_PICKUP_ROUTE = SHOP_ORDER_DETAIL_ROUTE;
export const DROPSHIP_ORDER_DETAIL_CUSTOMER_INVOICE_PREVIEW_ROUTE =
  'app-shop-order-packing-slip-page';
export const DROPSHIP_ORDER_RECIPIENT_INVOICE_PREVIEW_ROUTE =
  'app-shop-order-recipient-slip-page';
