import { defineAsyncComponent } from 'vue';

import type { DashboardSlot } from 'src/modules/dashboard/types/dashboardSlot';

const ThriftDashboardActions = defineAsyncComponent(
  () => import('./ThriftDashboardActions.vue'),
);
const ThriftInsightsPanel = defineAsyncComponent(() => import('./ThriftInsightsPanel.vue'));

/** Thrift ops home: action bar, charts/insights, then shortcuts. */
export const THRIFT_DASHBOARD_SLOTS: readonly DashboardSlot[] = [
  {
    id: 'thrift.ops.actions',
    scopes: ['app'],
    moduleKey: 'thrift_sales',
    action: 'view',
    parentGroupKey: 'thrift',
    kind: 'section',
    title: 'Actions',
    icon: 'ph ph-lightning',
    order: 5,
    component: ThriftDashboardActions,
  },
  {
    id: 'thrift.ops.insights',
    scopes: ['app'],
    moduleKey: 'thrift_reports',
    action: 'view',
    parentGroupKey: 'thrift',
    kind: 'section',
    title: 'Shop glance',
    icon: 'ph ph-chart-pie-slice',
    order: 10,
    component: ThriftInsightsPanel,
  },
  {
    id: 'thrift.sales.list',
    scopes: ['app'],
    moduleKey: 'thrift_sales',
    action: 'view',
    parentGroupKey: 'thrift',
    kind: 'shortcut',
    title: 'Sales & Invoices',
    caption: 'All invoices',
    icon: 'ph ph-receipt',
    order: 20,
    routeName: 'thrift-sales-page',
  },
  {
    id: 'thrift.sales.returns',
    scopes: ['app'],
    moduleKey: 'thrift_sales',
    action: 'view',
    parentGroupKey: 'thrift',
    kind: 'shortcut',
    title: 'Returns',
    caption: 'Post-pay returns hub',
    icon: 'ph ph-arrow-u-up-left',
    order: 30,
    routeName: 'thrift-sales-returns',
  },
  {
    id: 'thrift.stock.list',
    scopes: ['app'],
    moduleKey: 'thrift_stock',
    action: 'view',
    parentGroupKey: 'thrift',
    kind: 'shortcut',
    title: 'Thrift Stock',
    caption: 'Review stock inventory',
    icon: 'ph ph-package',
    order: 40,
    routeName: 'thrift-stock-page',
  },
  {
    id: 'thrift.shipment.list',
    scopes: ['app'],
    moduleKey: 'thrift_shipment',
    action: 'view',
    parentGroupKey: 'thrift',
    kind: 'shortcut',
    title: 'Shipments',
    caption: 'Shipment logs and intake',
    icon: 'ph ph-truck',
    order: 50,
    routeName: 'thrift-shipments-page',
  },
  {
    id: 'thrift.reports.hub',
    scopes: ['app'],
    moduleKey: 'thrift_reports',
    action: 'view',
    parentGroupKey: 'thrift',
    kind: 'shortcut',
    title: 'Reports',
    caption: 'Earn · COD · Purchases',
    icon: 'ph ph-chart-bar',
    order: 60,
    routeName: 'thrift-reports-page',
  },
];
