-- stock_locations catalog: bins/zones for parent warehouse (v2 locations CRUD)

begin;

-- ---------------------------------------------------------------------------
-- Enum
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'stock_location_kind') then
    create type public.stock_location_kind as enum (
      'zone',
      'bin',
      'staging',
      'returns'
    );
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table if not exists public.stock_locations (
  id bigint generated by default as identity primary key,
  parent_tenant_id bigint not null references public.tenants(id) on delete cascade,
  code text not null,
  name text not null,
  kind public.stock_location_kind not null default 'bin',
  is_default boolean not null default false,
  is_pickable boolean not null default true,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stock_locations_code_not_blank check (length(trim(code)) > 0),
  constraint stock_locations_name_not_blank check (length(trim(name)) > 0),
  constraint stock_locations_parent_code_unique unique (parent_tenant_id, code)
);

create index if not exists stock_locations_parent_sort_idx
  on public.stock_locations (parent_tenant_id, sort_order);

create index if not exists stock_locations_parent_active_idx
  on public.stock_locations (parent_tenant_id, is_active);

-- At most one default among active rows per parent
create unique index if not exists stock_locations_one_default_per_parent_idx
  on public.stock_locations (parent_tenant_id)
  where is_default = true and is_active = true;

drop trigger if exists trg_stock_locations_updated_at on public.stock_locations;
create trigger trg_stock_locations_updated_at
before update on public.stock_locations
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.stock_locations enable row level security;

drop policy if exists stock_locations_select on public.stock_locations;
create policy stock_locations_select on public.stock_locations
for select to authenticated
using (
  public.user_can_manage_parent_tenant(parent_tenant_id)
  or exists (
    select 1 from public.memberships m
    where m.tenant_id = stock_locations.parent_tenant_id
      and lower(trim(m.email)) = public.current_user_email()
      and m.is_active = true
  )
);

drop policy if exists stock_locations_all on public.stock_locations;
create policy stock_locations_all on public.stock_locations
for all to authenticated
using (public.user_can_manage_parent_tenant(parent_tenant_id))
with check (public.user_can_manage_parent_tenant(parent_tenant_id));

grant select, insert, update, delete on table public.stock_locations to authenticated;
grant usage, select on sequence public.stock_locations_id_seq to authenticated;

-- ---------------------------------------------------------------------------
-- Module actions (create / edit)
-- ---------------------------------------------------------------------------
insert into public.module_actions (module_key, action, scope, tenant_configurable, is_active)
values
  ('global_stock_location', 'create', 'app', true, true),
  ('global_stock_location', 'edit', 'app', true, true)
on conflict (module_key, action, scope) do update set
  is_active = true,
  tenant_configurable = true;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------
create or replace function public._assert_parent_warehouse_tenant(p_parent_tenant_id bigint)
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_parent_id bigint;
begin
  if p_parent_tenant_id is null then
    raise exception 'parent_tenant_id is required';
  end if;

  select parent_id into v_parent_id
  from public.tenants
  where id = p_parent_tenant_id;

  if not found then
    raise exception 'tenant not found';
  end if;

  if v_parent_id is not null then
    raise exception 'stock locations are only for parent warehouse tenants';
  end if;
end;
$$;

create or replace function public._can_view_stock_locations(p_parent_tenant_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.user_can_manage_parent_tenant(p_parent_tenant_id)
    or public.membership_has_module_action(p_parent_tenant_id, 'global_stock_location', 'view')
    or exists (
      select 1 from public.memberships m
      where m.tenant_id = p_parent_tenant_id
        and lower(trim(m.email)) = public.current_user_email()
        and m.is_active = true
    );
$$;

revoke all on function public._assert_parent_warehouse_tenant(bigint) from public;
revoke all on function public._can_view_stock_locations(bigint) from public;

-- ---------------------------------------------------------------------------
-- ensure_default_stock_locations
-- ---------------------------------------------------------------------------
create or replace function public.ensure_default_stock_locations(p_parent_tenant_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public._assert_parent_warehouse_tenant(p_parent_tenant_id);

  if not public._can_view_stock_locations(p_parent_tenant_id) then
    raise exception 'not allowed';
  end if;

  insert into public.stock_locations (
    parent_tenant_id, code, name, kind, is_default, is_pickable, sort_order, is_active
  )
  values
    (p_parent_tenant_id, 'MAIN', 'Main', 'bin', true, true, 0, true),
    (p_parent_tenant_id, 'RETURNS', 'Returns', 'returns', false, false, 100, true)
  on conflict (parent_tenant_id, code) do nothing;

  -- If MAIN exists but no active default, promote MAIN
  if not exists (
    select 1 from public.stock_locations
    where parent_tenant_id = p_parent_tenant_id
      and is_default = true
      and is_active = true
  ) then
    update public.stock_locations
    set is_default = true
    where parent_tenant_id = p_parent_tenant_id
      and code = 'MAIN'
      and is_active = true;
  end if;
end;
$$;

revoke all on function public.ensure_default_stock_locations(bigint) from public;
grant execute on function public.ensure_default_stock_locations(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- list_stock_locations
-- ---------------------------------------------------------------------------
create or replace function public.list_stock_locations(
  p_parent_tenant_id bigint,
  p_include_inactive boolean default false
)
returns setof public.stock_locations
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public._assert_parent_warehouse_tenant(p_parent_tenant_id);

  if not public._can_view_stock_locations(p_parent_tenant_id) then
    raise exception 'not allowed';
  end if;

  perform public.ensure_default_stock_locations(p_parent_tenant_id);

  return query
  select l.*
  from public.stock_locations l
  where l.parent_tenant_id = p_parent_tenant_id
    and (p_include_inactive or l.is_active = true)
  order by l.sort_order asc, l.code asc, l.id asc;
end;
$$;

revoke all on function public.list_stock_locations(bigint, boolean) from public;
grant execute on function public.list_stock_locations(bigint, boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- upsert_stock_location
-- ---------------------------------------------------------------------------
create or replace function public.upsert_stock_location(
  p_parent_tenant_id bigint,
  p_code text,
  p_name text,
  p_kind public.stock_location_kind default 'bin',
  p_is_pickable boolean default true,
  p_sort_order integer default 0,
  p_is_active boolean default true,
  p_is_default boolean default false,
  p_id bigint default null
)
returns public.stock_locations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_name text;
  v_row public.stock_locations%rowtype;
  v_action text;
begin
  perform public._assert_parent_warehouse_tenant(p_parent_tenant_id);

  v_action := case when p_id is null then 'create' else 'edit' end;

  if not (
    public.user_can_manage_parent_tenant(p_parent_tenant_id)
    or public.membership_has_module_action(p_parent_tenant_id, 'global_stock_location', v_action)
  ) then
    raise exception 'not allowed';
  end if;

  v_code := upper(trim(coalesce(p_code, '')));
  v_name := trim(coalesce(p_name, ''));

  if length(v_code) = 0 then
    raise exception 'code is required';
  end if;
  if length(v_name) = 0 then
    raise exception 'name is required';
  end if;

  if p_kind is null then
    raise exception 'kind is required';
  end if;

  -- Clear other defaults before setting this one (active default uniqueness)
  if coalesce(p_is_default, false) and coalesce(p_is_active, true) then
    update public.stock_locations
    set is_default = false
    where parent_tenant_id = p_parent_tenant_id
      and is_default = true
      and (p_id is null or id <> p_id);
  end if;

  if p_id is null then
    insert into public.stock_locations (
      parent_tenant_id,
      code,
      name,
      kind,
      is_default,
      is_pickable,
      sort_order,
      is_active
    )
    values (
      p_parent_tenant_id,
      v_code,
      v_name,
      p_kind,
      coalesce(p_is_default, false),
      coalesce(p_is_pickable, true),
      coalesce(p_sort_order, 0),
      coalesce(p_is_active, true)
    )
    returning * into v_row;
  else
    update public.stock_locations
    set
      code = v_code,
      name = v_name,
      kind = p_kind,
      is_default = coalesce(p_is_default, is_default),
      is_pickable = coalesce(p_is_pickable, is_pickable),
      sort_order = coalesce(p_sort_order, sort_order),
      is_active = coalesce(p_is_active, is_active)
    where id = p_id
      and parent_tenant_id = p_parent_tenant_id
    returning * into v_row;

    if not found then
      raise exception 'location not found';
    end if;
  end if;

  -- Must keep one active default when deactivating/unsetting previous default
  if not exists (
    select 1 from public.stock_locations
    where parent_tenant_id = p_parent_tenant_id
      and is_default = true
      and is_active = true
  ) then
    update public.stock_locations
    set is_default = true
    where id = (
      select id from public.stock_locations
      where parent_tenant_id = p_parent_tenant_id
        and is_active = true
      order by case when code = 'MAIN' then 0 else 1 end, sort_order, id
      limit 1
    );
  end if;

  select * into v_row
  from public.stock_locations
  where id = v_row.id;

  return v_row;
end;
$$;

revoke all on function public.upsert_stock_location(
  bigint, text, text, public.stock_location_kind, boolean, integer, boolean, boolean, bigint
) from public;
grant execute on function public.upsert_stock_location(
  bigint, text, text, public.stock_location_kind, boolean, integer, boolean, boolean, bigint
) to authenticated;

-- ---------------------------------------------------------------------------
-- set_default_stock_location
-- ---------------------------------------------------------------------------
create or replace function public.set_default_stock_location(p_id bigint)
returns public.stock_locations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.stock_locations%rowtype;
begin
  select * into v_row
  from public.stock_locations
  where id = p_id
  for update;

  if not found then
    raise exception 'location not found';
  end if;

  perform public._assert_parent_warehouse_tenant(v_row.parent_tenant_id);

  if not (
    public.user_can_manage_parent_tenant(v_row.parent_tenant_id)
    or public.membership_has_module_action(v_row.parent_tenant_id, 'global_stock_location', 'edit')
  ) then
    raise exception 'not allowed';
  end if;

  if not v_row.is_active then
    raise exception 'cannot set inactive location as default';
  end if;

  update public.stock_locations
  set is_default = false
  where parent_tenant_id = v_row.parent_tenant_id
    and is_default = true
    and id <> p_id;

  update public.stock_locations
  set is_default = true
  where id = p_id
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.set_default_stock_location(bigint) from public;
grant execute on function public.set_default_stock_location(bigint) to authenticated;

commit;
