-- Migration: Tag Catalog T1 — Schema, Seeds, and RPCs
begin;

-- 1. Create tag_categories
create table if not exists public.tag_categories (
  id bigint generated by default as identity primary key,
  module_key text not null,
  code text not null,
  name text not null,
  cardinality text not null check (cardinality in ('single', 'many')),
  is_system boolean not null default true,
  tenant_id bigint references public.tenants(id) on delete cascade null,
  sort_order integer null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists tag_categories_system_unique
  on public.tag_categories(module_key, code)
  where tenant_id is null;

create unique index if not exists tag_categories_tenant_unique
  on public.tag_categories(tenant_id, module_key, code)
  where tenant_id is not null;

-- 2. Extend tags table
alter table public.tags
  add column if not exists category_id bigint references public.tag_categories(id) on delete cascade null,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists is_system boolean not null default true,
  add column if not exists is_active boolean not null default true;

create unique index if not exists tags_category_slug_unique
  on public.tags(category_id, slug)
  where category_id is not null;

-- 3. RLS Policies
alter table public.tag_categories enable row level security;

drop policy if exists tag_categories_select on public.tag_categories;
create policy tag_categories_select on public.tag_categories
  for select to authenticated, anon
  using (
    is_system = true
    or tenant_id is null
    or (tenant_id is not null and public.has_active_tenant_membership(tenant_id))
  );

drop policy if exists tag_categories_insert on public.tag_categories;
create policy tag_categories_insert on public.tag_categories
  for insert to authenticated
  with check (
    is_system = false
    and tenant_id is not null
    and public.has_active_tenant_membership(tenant_id)
  );

drop policy if exists tag_categories_update on public.tag_categories;
create policy tag_categories_update on public.tag_categories
  for update to authenticated
  using (
    is_system = false
    and tenant_id is not null
    and public.has_active_tenant_membership(tenant_id)
  );

drop policy if exists tag_categories_delete on public.tag_categories;
create policy tag_categories_delete on public.tag_categories
  for delete to authenticated
  using (
    is_system = false
    and tenant_id is not null
    and public.has_active_tenant_membership(tenant_id)
  );

-- Update tags RLS to allow reading system tags
drop policy if exists tags_select on public.tags;
create policy tags_select on public.tags
  for select to authenticated, anon
  using (
    is_system = true
    or tenant_id is null
    or (tenant_id is not null and public.has_active_tenant_membership(tenant_id))
    or exists (
      select 1 
      from public.memberships m1
      join public.memberships m2 on m2.tenant_id = m1.tenant_id
      where lower(trim(m1.email)) = public.current_user_email()
        and lower(trim(m2.email)) = tags.created_by_email
        and m1.is_active = true
        and m2.is_active = true
    )
  );

grant select, insert, update, delete on public.tag_categories to authenticated;
grant usage, select on sequence public.tag_categories_id_seq to authenticated;

-- 4. Seed system categories and tags

-- Category 1: stock_grade / warehouse
insert into public.tag_categories (module_key, code, name, cardinality, is_system, tenant_id, sort_order, is_active)
values ('stock_grade', 'warehouse', 'Warehouse', 'single', true, null, 1, true)
on conflict (module_key, code) where tenant_id is null
do update set name = excluded.name, cardinality = excluded.cardinality, sort_order = excluded.sort_order;

-- Category 2: stock_grade / produce
insert into public.tag_categories (module_key, code, name, cardinality, is_system, tenant_id, sort_order, is_active)
values ('stock_grade', 'produce', 'Produce', 'single', true, null, 2, true)
on conflict (module_key, code) where tenant_id is null
do update set name = excluded.name, cardinality = excluded.cardinality, sort_order = excluded.sort_order;

-- Category 3: stock_grade / clothing
insert into public.tag_categories (module_key, code, name, cardinality, is_system, tenant_id, sort_order, is_active)
values ('stock_grade', 'clothing', 'Clothing', 'single', true, null, 3, true)
on conflict (module_key, code) where tenant_id is null
do update set name = excluded.name, cardinality = excluded.cardinality, sort_order = excluded.sort_order;

-- Category 4: color / default
insert into public.tag_categories (module_key, code, name, cardinality, is_system, tenant_id, sort_order, is_active)
values ('color', 'default', 'Default', 'single', true, null, 1, true)
on conflict (module_key, code) where tenant_id is null
do update set name = excluded.name, cardinality = excluded.cardinality, sort_order = excluded.sort_order;

-- Seed tags
do $$
declare
  v_cat_wh bigint;
  v_cat_prod bigint;
  v_cat_cloth bigint;
  v_cat_color bigint;
begin
  select id into v_cat_wh from public.tag_categories where module_key = 'stock_grade' and code = 'warehouse' and tenant_id is null;
  select id into v_cat_prod from public.tag_categories where module_key = 'stock_grade' and code = 'produce' and tenant_id is null;
  select id into v_cat_cloth from public.tag_categories where module_key = 'stock_grade' and code = 'clothing' and tenant_id is null;
  select id into v_cat_color from public.tag_categories where module_key = 'color' and code = 'default' and tenant_id is null;

  -- Warehouse tags
  insert into public.tags (category_id, slug, name, color, metadata, sort_order, is_system, is_active, group_name, type, created_by_email)
  values
    (v_cat_wh, 'standard', 'Standard', '#22c55e', '{"maps_to_availability": "sellable"}'::jsonb, 1, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_wh, 'open_box', 'Open box', '#3b82f6', '{"maps_to_availability": "sellable"}'::jsonb, 2, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_wh, 'box_damage', 'Box damage', '#f59e0b', '{"maps_to_availability": "sellable"}'::jsonb, 3, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_wh, 'box_less', 'Box less', '#8b5cf6', '{"maps_to_availability": "sellable"}'::jsonb, 4, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_wh, 'badly_damaged', 'Badly damaged', '#ef4444', '{"maps_to_availability": "unsellable"}'::jsonb, 5, true, true, 'stock_grade', 'stock_grade', 'system')
  on conflict (category_id, slug) where category_id is not null
  do update set name = excluded.name, color = excluded.color, metadata = excluded.metadata, sort_order = excluded.sort_order;

  -- Produce tags
  insert into public.tags (category_id, slug, name, color, metadata, sort_order, is_system, is_active, group_name, type, created_by_email)
  values
    (v_cat_prod, 'fresh', 'Fresh', '#22c55e', '{"maps_to_availability": "sellable"}'::jsonb, 1, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_prod, 'ripe', 'Ripe', '#3b82f6', '{"maps_to_availability": "sellable"}'::jsonb, 2, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_prod, 'seconds', 'Seconds', '#f59e0b', '{"maps_to_availability": "sellable"}'::jsonb, 3, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_prod, 'waste', 'Waste', '#ef4444', '{"maps_to_availability": "unsellable"}'::jsonb, 4, true, true, 'stock_grade', 'stock_grade', 'system')
  on conflict (category_id, slug) where category_id is not null
  do update set name = excluded.name, color = excluded.color, metadata = excluded.metadata, sort_order = excluded.sort_order;

  -- Clothing tags
  insert into public.tags (category_id, slug, name, color, metadata, sort_order, is_system, is_active, group_name, type, created_by_email)
  values
    (v_cat_cloth, 'new', 'New', '#22c55e', '{"maps_to_availability": "sellable"}'::jsonb, 1, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_cloth, 'display', 'Display', '#3b82f6', '{"maps_to_availability": "sellable"}'::jsonb, 2, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_cloth, 'defect', 'Defect', '#f59e0b', '{"maps_to_availability": "sellable"}'::jsonb, 3, true, true, 'stock_grade', 'stock_grade', 'system'),
    (v_cat_cloth, 'return', 'Return', '#8b5cf6', '{"maps_to_availability": "sellable"}'::jsonb, 4, true, true, 'stock_grade', 'stock_grade', 'system')
  on conflict (category_id, slug) where category_id is not null
  do update set name = excluded.name, color = excluded.color, metadata = excluded.metadata, sort_order = excluded.sort_order;

  -- Color tags
  insert into public.tags (category_id, slug, name, color, metadata, sort_order, is_system, is_active, group_name, type, created_by_email)
  values
    (v_cat_color, 'black', 'Black', '#111827', '{}'::jsonb, 1, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'white', 'White', '#F9FAFB', '{}'::jsonb, 2, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'grey', 'Grey', '#6B7280', '{}'::jsonb, 3, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'red', 'Red', '#DC2626', '{}'::jsonb, 4, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'blue', 'Blue', '#2563EB', '{}'::jsonb, 5, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'green', 'Green', '#16A34A', '{}'::jsonb, 6, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'yellow', 'Yellow', '#EAB308', '{}'::jsonb, 7, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'orange', 'Orange', '#EA580C', '{}'::jsonb, 8, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'pink', 'Pink', '#DB2777', '{}'::jsonb, 9, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'purple', 'Purple', '#7C3AED', '{}'::jsonb, 10, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'brown', 'Brown', '#92400E', '{}'::jsonb, 11, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'beige', 'Beige', '#D4A574', '{}'::jsonb, 12, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'navy', 'Navy', '#1E3A5F', '{}'::jsonb, 13, true, true, 'color', 'color', 'system'),
    (v_cat_color, 'multicolor', 'Multicolor', '#A855F7', '{}'::jsonb, 14, true, true, 'color', 'color', 'system')
  on conflict (category_id, slug) where category_id is not null
  do update set name = excluded.name, color = excluded.color, metadata = excluded.metadata, sort_order = excluded.sort_order;
end $$;

-- 5. RPCs

-- list_tag_categories
create or replace function public.list_tag_categories(
  p_module_key text default null
)
returns json
language plpgsql
security definer
as $$
declare
  v_res json;
begin
  select coalesce(json_agg(row_to_json(c)), '[]'::json)
  into v_res
  from (
    select
      tc.id,
      tc.module_key,
      tc.code,
      tc.name,
      tc.cardinality,
      tc.is_system,
      tc.tenant_id,
      tc.sort_order,
      tc.is_active,
      tc.created_at
    from public.tag_categories tc
    where tc.is_active = true
      and (p_module_key is null or tc.module_key = p_module_key)
    order by tc.sort_order asc nulls last, tc.id asc
  ) c;

  return v_res;
end;
$$;

-- list_tags_for_category
create or replace function public.list_tags_for_category(
  p_category_id bigint default null,
  p_module_key text default null,
  p_code text default null
)
returns json
language plpgsql
security definer
as $$
declare
  v_category_id bigint;
  v_res json;
begin
  if p_category_id is not null then
    v_category_id := p_category_id;
  elsif p_module_key is not null and p_code is not null then
    select tc.id into v_category_id
    from public.tag_categories tc
    where tc.module_key = p_module_key
      and tc.code = p_code
      and tc.is_active = true
    limit 1;
  end if;

  if v_category_id is null then
    return '[]'::json;
  end if;

  select coalesce(json_agg(row_to_json(t)), '[]'::json)
  into v_res
  from (
    select
      tg.id,
      tg.category_id,
      tg.slug,
      tg.name,
      tg.color,
      tg.metadata,
      tg.sort_order,
      tg.is_system,
      tg.is_active,
      tg.tenant_id,
      tg.group_name,
      tg.type
    from public.tags tg
    where tg.category_id = v_category_id
      and tg.is_active = true
    order by tg.sort_order asc nulls last, tg.id asc
  ) t;

  return v_res;
end;
$$;

-- get_tag_by_slug
create or replace function public.get_tag_by_slug(
  p_category_id bigint default null,
  p_module_key text default null,
  p_code text default null,
  p_slug text default null
)
returns json
language plpgsql
security definer
as $$
declare
  v_category_id bigint;
  v_res json;
begin
  if p_slug is null then
    return null;
  end if;

  if p_category_id is not null then
    v_category_id := p_category_id;
  elsif p_module_key is not null and p_code is not null then
    select tc.id into v_category_id
    from public.tag_categories tc
    where tc.module_key = p_module_key
      and tc.code = p_code
      and tc.is_active = true
    limit 1;
  end if;

  if v_category_id is null then
    return null;
  end if;

  select row_to_json(t)
  into v_res
  from (
    select
      tg.id,
      tg.category_id,
      tg.slug,
      tg.name,
      tg.color,
      tg.metadata,
      tg.sort_order,
      tg.is_system,
      tg.is_active,
      tg.tenant_id,
      tg.group_name,
      tg.type
    from public.tags tg
    where tg.category_id = v_category_id
      and tg.slug = p_slug
      and tg.is_active = true
    limit 1
  ) t;

  return v_res;
end;
$$;

grant execute on function public.list_tag_categories(text) to authenticated, anon;
grant execute on function public.list_tags_for_category(bigint, text, text) to authenticated, anon;
grant execute on function public.get_tag_by_slug(bigint, text, text, text) to authenticated, anon;

commit;
