-- Vendor discount as financial record only (no stock / outcome mutation).

create table if not exists public.global_shipment_outcome_vendor_credits (
  id bigint generated by default as identity primary key,
  parent_tenant_id bigint not null references public.tenants (id) on delete cascade,
  shipment_id bigint not null references public.global_shipments (id) on delete cascade,
  shipment_item_id bigint not null references public.global_shipment_items (id) on delete cascade,
  outcome_id bigint not null references public.global_shipment_item_outcomes (id) on delete restrict,
  quantity integer not null,
  previous_purchase_price numeric not null,
  new_purchase_price numeric not null,
  credit_amount numeric not null,
  created_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint global_shipment_outcome_vendor_credits_quantity_check check (quantity >= 1),
  constraint global_shipment_outcome_vendor_credits_prices_check check (
    previous_purchase_price >= 0 and new_purchase_price >= 0
  )
);

create index if not exists global_shipment_outcome_vendor_credits_shipment_idx
  on public.global_shipment_outcome_vendor_credits (shipment_id);

create index if not exists global_shipment_outcome_vendor_credits_outcome_idx
  on public.global_shipment_outcome_vendor_credits (outcome_id);

create trigger trg_global_shipment_outcome_vendor_credits_set_updated_at
  before update on public.global_shipment_outcome_vendor_credits
  for each row execute function public.set_updated_at();

alter table public.global_shipment_outcome_vendor_credits enable row level security;

create policy global_shipment_outcome_vendor_credits_all
  on public.global_shipment_outcome_vendor_credits
  to authenticated
  using (public.user_can_manage_parent_tenant(parent_tenant_id))
  with check (public.user_can_manage_parent_tenant(parent_tenant_id));

grant select, insert on table public.global_shipment_outcome_vendor_credits to authenticated;
grant usage, select on sequence public.global_shipment_outcome_vendor_credits_id_seq to authenticated;

create or replace function public.apply_shipment_outcome_vendor_discount(
  p_shipment_id bigint,
  p_source_outcome_id bigint,
  p_quantity integer,
  p_new_purchase_price numeric
)
returns jsonb
language plpgsql
security definer
set search_path to public
as $$
declare
  v_ship public.global_shipments%rowtype;
  v_src public.global_shipment_item_outcomes%rowtype;
  v_parent bigint;
  v_prev_price numeric;
  v_credit numeric;
  v_row_id bigint;
begin
  if p_quantity is null or p_quantity < 1 then
    raise exception 'quantity must be at least 1';
  end if;

  if p_new_purchase_price is null or p_new_purchase_price < 0 then
    raise exception 'purchase price must be >= 0';
  end if;

  select * into v_ship from public.global_shipments where id = p_shipment_id for update;
  if not found then
    raise exception 'shipment not found';
  end if;

  v_parent := v_ship.parent_tenant_id;
  if not public.user_can_manage_parent_tenant(v_parent) then
    raise exception 'not allowed';
  end if;

  if v_ship.status = 'cancelled' then
    raise exception 'shipment is cancelled';
  end if;

  if coalesce(v_ship.is_closed, false) then
    raise exception 'shipment is closed';
  end if;

  if v_ship.status <> 'received' then
    raise exception 'shipment must be received to record vendor credit';
  end if;

  select o.* into v_src
  from public.global_shipment_item_outcomes o
  inner join public.global_shipment_items gsi on gsi.id = o.shipment_item_id
  where o.id = p_source_outcome_id
    and gsi.shipment_id = p_shipment_id;

  if not found then
    raise exception 'outcome not found on shipment';
  end if;

  if v_src.reason = 'ordered'::public.global_shipment_outcome_reason then
    raise exception 'cannot credit ordered row';
  end if;

  if v_src.kind <> 'sellable'::public.global_shipment_outcome_kind then
    raise exception 'outcome must be sellable';
  end if;

  if p_quantity > v_src.quantity then
    raise exception 'quantity % exceeds split qty %', p_quantity, v_src.quantity;
  end if;

  v_prev_price := coalesce(v_src.purchase_price, 0);
  v_credit := round((v_prev_price - p_new_purchase_price) * p_quantity, 4);

  insert into public.global_shipment_outcome_vendor_credits (
    parent_tenant_id,
    shipment_id,
    shipment_item_id,
    outcome_id,
    quantity,
    previous_purchase_price,
    new_purchase_price,
    credit_amount,
    created_by_email
  ) values (
    v_parent,
    p_shipment_id,
    v_src.shipment_item_id,
    v_src.id,
    p_quantity,
    v_prev_price,
    p_new_purchase_price,
    v_credit,
    public.current_user_email()
  )
  returning id into v_row_id;

  return jsonb_build_object(
    'mode', 'record',
    'id', v_row_id,
    'shipment_id', p_shipment_id,
    'outcome_id', v_src.id,
    'quantity', p_quantity,
    'previous_purchase_price', v_prev_price,
    'new_purchase_price', p_new_purchase_price,
    'credit_amount', v_credit
  );
end;
$$;

create or replace function public.list_shipment_outcome_vendor_credits(p_shipment_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path to public
as $$
declare
  v_parent bigint;
begin
  select parent_tenant_id into v_parent
  from public.global_shipments
  where id = p_shipment_id;

  if v_parent is null then
    raise exception 'shipment not found';
  end if;

  if not public.user_can_manage_parent_tenant(v_parent) then
    raise exception 'not allowed';
  end if;

  return coalesce(
    (
      select jsonb_agg(row_to_json(r) order by r.created_at desc)
      from (
        select
          c.id,
          c.shipment_id,
          c.shipment_item_id,
          c.outcome_id,
          c.quantity,
          c.previous_purchase_price,
          c.new_purchase_price,
          c.credit_amount,
          c.created_by_email,
          c.created_at,
          gsi.name as item_name
        from public.global_shipment_outcome_vendor_credits c
        inner join public.global_shipment_items gsi on gsi.id = c.shipment_item_id
        where c.shipment_id = p_shipment_id
      ) r
    ),
    '[]'::jsonb
  );
end;
$$;

grant execute on function public.apply_shipment_outcome_vendor_discount(bigint, bigint, integer, numeric) to authenticated;
grant execute on function public.list_shipment_outcome_vendor_credits(bigint) to authenticated;
