-- Profiles: replacement for billing_profiles (phase 1 — dual table; drop billing_profiles later).
-- Same id as billing_profiles on backfill so FK cutover can reuse ids.

do $$ begin
  create type public.profile_party_type as enum (
    'tenant',
    'customer',
    'company',
    'vendor',
    'cargo',
    'courier',
    'investor'
  );
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  parent_tenant_id bigint not null references public.tenants (id) on delete restrict,
  profile_type public.profile_party_type not null default 'customer',
  subject_id bigint not null,
  name text not null,
  email text,
  phone text,
  phone_country_code text not null default '+880',
  address text,
  is_phone_unique boolean not null default true,
  accent_color text,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_party_unique unique (parent_tenant_id, profile_type, subject_id)
);

create unique index if not exists profiles_parent_phone_uidx
  on public.profiles (parent_tenant_id, phone_country_code, phone)
  where (
    phone is not null
    and btrim(phone) <> ''
    and is_phone_unique
  );

create index if not exists profiles_parent_tenant_id_idx
  on public.profiles (parent_tenant_id);

create index if not exists profiles_profile_type_idx
  on public.profiles (profile_type);

-- Backfill: subject_id = billing_profiles.id (one row per profile; avoids duplicate customer_group_id).
insert into public.profiles (
  id,
  parent_tenant_id,
  profile_type,
  subject_id,
  name,
  email,
  phone,
  phone_country_code,
  address,
  is_phone_unique,
  accent_color,
  is_active,
  deleted_at,
  created_at,
  updated_at
)
overriding system value
select
  bp.id,
  bp.parent_tenant_id,
  'customer'::public.profile_party_type,
  bp.id,
  bp.name,
  bp.email,
  bp.phone,
  bp.phone_country_code,
  bp.address,
  bp.is_phone_unique,
  coalesce(cg.accent_color, bp.color),
  coalesce(cg.is_active, true),
  cg.deleted_at,
  bp.created_at,
  bp.updated_at
from public.billing_profiles bp
left join public.customer_groups cg on cg.id = bp.customer_group_id
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.profiles', 'id'),
  coalesce((select max(id) from public.profiles), 1),
  true
);

create or replace function public.trg_sync_profile_from_billing_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_accent text;
  v_active boolean;
  v_deleted timestamptz;
begin
  if new.customer_group_id is not null then
    select cg.accent_color, cg.is_active, cg.deleted_at
    into v_accent, v_active, v_deleted
    from public.customer_groups cg
    where cg.id = new.customer_group_id;
  end if;

  insert into public.profiles (
    id,
    parent_tenant_id,
    profile_type,
    subject_id,
    name,
    email,
    phone,
    phone_country_code,
    address,
    is_phone_unique,
    accent_color,
    is_active,
    deleted_at,
    created_at,
    updated_at
  )
  overriding system value
  values (
    new.id,
    new.parent_tenant_id,
    'customer'::public.profile_party_type,
    new.id,
    new.name,
    new.email,
    new.phone,
    new.phone_country_code,
    new.address,
    new.is_phone_unique,
    coalesce(v_accent, new.color),
    coalesce(v_active, true),
    v_deleted,
    new.created_at,
    new.updated_at
  )
  on conflict (id) do update set
    parent_tenant_id = excluded.parent_tenant_id,
    name = excluded.name,
    email = excluded.email,
    phone = excluded.phone,
    phone_country_code = excluded.phone_country_code,
    address = excluded.address,
    is_phone_unique = excluded.is_phone_unique,
    accent_color = excluded.accent_color,
    is_active = excluded.is_active,
    deleted_at = excluded.deleted_at,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists trg_billing_profiles_sync_profile on public.billing_profiles;

create trigger trg_billing_profiles_sync_profile
  after insert or update on public.billing_profiles
  for each row
  execute function public.trg_sync_profile_from_billing_profile();

drop trigger if exists trg_profiles_set_updated_at on public.profiles;

create trigger trg_profiles_set_updated_at
  before update on public.profiles
  for each row
  execute function public.set_updated_at();

alter table public.profiles enable row level security;

drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_write on public.profiles;

create policy profiles_select on public.profiles
  for select to authenticated
  using (
    public.has_active_tenant_membership(parent_tenant_id)
    or public.user_can_manage_parent_tenant(parent_tenant_id)
    or exists (
      select 1
      from public.memberships m
      where m.tenant_id = profiles.parent_tenant_id
        and lower(trim(both from m.email)) = public.current_user_email()
        and m.is_active
    )
  );

create policy profiles_write on public.profiles
  to authenticated
  using (
    public.membership_has_module_action(parent_tenant_id, 'billing_profile', 'edit')
  )
  with check (
    public.membership_has_module_action(parent_tenant_id, 'billing_profile', 'edit')
  );

grant select, insert, update, delete on table public.profiles to authenticated;
grant usage, select on sequence public.profiles_id_seq to authenticated;
