-- Procurement inbound target schema (docs/features/procurement_stock/spec.md US-7–US-9).

alter table public.global_shipments
  add column if not exists is_closed boolean not null default false;

comment on column public.global_shipments.is_closed is
  'When true, shipment is read-only (close action). Distinct from costs_locked and is_archived.';

do $$
begin
  if not exists (
    select 1 from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'global_shipment_outcome_kind'
  ) then
    create type public.global_shipment_outcome_kind as enum ('sellable', 'unsellable');
  end if;

  if not exists (
    select 1 from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'global_shipment_outcome_reason'
  ) then
    create type public.global_shipment_outcome_reason as enum (
      'general',
      'vendor_discount',
      'missing',
      'damaged',
      'other'
    );
  end if;
end $$;

create table if not exists public.global_shipment_item_outcomes (
  id bigint generated by default as identity primary key,
  parent_tenant_id bigint not null references public.tenants (id) on delete cascade,
  shipment_item_id bigint not null references public.global_shipment_items (id) on delete cascade,
  quantity integer not null,
  kind public.global_shipment_outcome_kind not null,
  reason public.global_shipment_outcome_reason not null,
  purchase_price numeric not null default 0,
  cost numeric,
  description text,
  batch_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint global_shipment_item_outcomes_quantity_check check (quantity >= 0),
  constraint global_shipment_item_outcomes_purchase_price_check check (purchase_price >= 0),
  constraint global_shipment_item_outcomes_cost_check check (cost is null or cost >= 0)
);

create index if not exists global_shipment_item_outcomes_item_idx
  on public.global_shipment_item_outcomes (shipment_item_id);

create index if not exists global_shipment_item_outcomes_parent_idx
  on public.global_shipment_item_outcomes (parent_tenant_id);

create trigger trg_global_shipment_item_outcomes_set_updated_at
  before update on public.global_shipment_item_outcomes
  for each row execute function public.set_updated_at();

alter table public.global_shipment_item_outcomes enable row level security;

create policy global_shipment_item_outcomes_all on public.global_shipment_item_outcomes
  to authenticated
  using (public.user_can_manage_parent_tenant(parent_tenant_id))
  with check (public.user_can_manage_parent_tenant(parent_tenant_id));

create table if not exists public.global_shipment_local_costs (
  id bigint generated by default as identity primary key,
  parent_tenant_id bigint not null references public.tenants (id) on delete cascade,
  shipment_id bigint not null references public.global_shipments (id) on delete cascade,
  section_id bigint references public.global_shipment_sections (id) on delete set null,
  description text not null,
  amount numeric not null,
  currency_id bigint references public.global_currencies (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint global_shipment_local_costs_description_not_blank
    check (length(trim(description)) > 0),
  constraint global_shipment_local_costs_amount_check check (amount >= 0)
);

create index if not exists global_shipment_local_costs_shipment_idx
  on public.global_shipment_local_costs (shipment_id);

create index if not exists global_shipment_local_costs_parent_idx
  on public.global_shipment_local_costs (parent_tenant_id);

create trigger trg_global_shipment_local_costs_set_updated_at
  before update on public.global_shipment_local_costs
  for each row execute function public.set_updated_at();

alter table public.global_shipment_local_costs enable row level security;

create policy global_shipment_local_costs_all on public.global_shipment_local_costs
  to authenticated
  using (public.user_can_manage_parent_tenant(parent_tenant_id))
  with check (public.user_can_manage_parent_tenant(parent_tenant_id));

alter table public.global_stocks
  add column if not exists outcome_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'global_stocks_outcome_id_fkey'
  ) then
    alter table public.global_stocks
      add constraint global_stocks_outcome_id_fkey
      foreign key (outcome_id) references public.global_shipment_item_outcomes (id) on delete set null;
  end if;
end $$;

create index if not exists global_stocks_outcome_id_idx
  on public.global_stocks (outcome_id)
  where outcome_id is not null;

grant all on table public.global_shipment_item_outcomes to authenticated;
grant all on sequence public.global_shipment_item_outcomes_id_seq to authenticated;
grant all on table public.global_shipment_local_costs to authenticated;
grant all on sequence public.global_shipment_local_costs_id_seq to authenticated;
