-- W7a (20270817000040) is language sql and checks tag_categories / tags.category_id
-- at CREATE time. Tag catalog T1 is timestamped later (20270819000000).
-- Pre-create the same IF NOT EXISTS objects so a fresh reset can replay W7a.
-- T1 remains the source of indexes, RLS, seeds, and RPCs.
-- Safe on prod: no-op if T1 already applied (include-all may insert this out of order).

begin;

create table if not exists public.tag_categories (
  id bigint generated by default as identity primary key,
  module_key text not null,
  code text not null,
  name text not null,
  cardinality text not null check (cardinality in ('single', 'many')),
  is_system boolean not null default true,
  tenant_id bigint references public.tenants(id) on delete cascade null,
  sort_order integer null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.tags
  add column if not exists category_id bigint references public.tag_categories(id) on delete cascade null,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists is_system boolean not null default true,
  add column if not exists is_active boolean not null default true;

commit;
